### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by patrikglanemann** [chingu-voyages/v34-geckos-team-04#12]
**__Feature Description__**
User should be able to create and change Events to shedule a meeting. 

**__Major User Stories/tasks__**
- [x] List Events on Event Page
- [ ] Fetch Events from Google Calendar
- [x] #32 
- [x] #33
- [x] #31
- [x] Add styling to Events page

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
