### ISSUE TITLE
Menu bar functionality

### ISSUE THREAD

**Issue by patrikglanemann** [chingu-voyages/v34-geckos-team-04#47]
**__Task Description__**
Add functionality to menu bar.

**__Technical Considerations__**
- [x] Redirect to Event Page on home-btn click
- [x] Redirect to Event Create Page on create-btn click
- [x] Open Google Calendar on calendar-btn click

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.
