### ISSUE TITLE
Sub-menu bar on event detail page

### ISSUE THREAD

**Issue by patrikglanemann** [chingu-voyages/v34-geckos-team-04#48]
**__Task Description__**
Create a sub-menu  bar component for event detail page according to desgn specifications.

**__Technical Considerations__**
- [x] Redirect to availability page on availability-btn click
- [x] Copy event link on share-btn click
- [x] Add user notification that link has been copied and can be shared via a messenger 
- [x] Redirect to "edit event page" on edit-btn click
- [x] Redirect to message page on message-btn click
- [x] Add styling

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.
