### ISSUE TITLE
EventInfo

### ISSUE THREAD

**Issue by patrikglanemann** [chingu-voyages/v34-geckos-team-04#49]
**__Task Description__**
Make EventInfo editable and add styling. 

**__Technical Considerations__**
- [x] Add styling according to design template
- [x] Integrate sub menu bar 
- [x] Add edit feature

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.
